name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      gst_repo:
        description: 'gst-plugins-rs source repo'
        required: true
        default: 'https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git'
        type: string
      gst_version:
        description: 'gst-plugins-rs branch/tag'
        required: true
        default: 'main'
        type: string
      gst_plugin:
        description: 'path to plugin'
        required: true
        default: 'audio/spotify'
        type: string

jobs:
  build:
    uses: ./.github/workflows/base.yml
    with:
      gst_repo: ${{ github.event.inputs.gst_repo }}
      gst_version: ${{ github.event.inputs.gst_version }}
      gst_plugin: ${{ github.event.inputs.gst_plugin }}

  release:
    name: Prepeare release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download everything we built
        uses: actions/download-artifact@v4
        with:
          path: goodies
          merge-multiple: true

      - run: ls -R goodies  
      
      - name: Draft the release
        uses: softprops/action-gh-release@v1
        with:
          files: goodies/*
          draft: true
          body: 'gst-plugins-rs plugin ${{ github.event.inputs.gst_plugin }} version ${{ github.event.inputs.gst_version }}'
          
        
